name: PHP Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli
        coverage: none

    - name: Install dependencies
      run: composer install

    - name: Run login.php tests
      run: composer test -- --filter logintest

    - name: Run shoppingcart.php tests
      run: composer test -- --filter shoppingcart

    - name: Run search.php tests
      run: composer test -- --filter search

    - name: Run handleorder.php tests
      run: composer test -- --filter handleorder

    - name: Run pay.php tests
      run: composer test -- --filter pay

    - name: Run post.php tests
      run: composer test -- --filter post
